[CmdletBinding(SupportsShouldProcess, ConfirmImpact = "High")]
param(
    [switch] $Force
)

. (Join-Path $PSScriptRoot "Identity.Common.ps1")

function New-IdentitySecret {
    param(
        [int] $ByteCount = 32,
        [switch] $AsPassword
    )

    $bytes = [byte[]]::new($ByteCount)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $token = [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
    if ($AsPassword) {
        return "A1!$token"
    }
    return $token
}

if ((Test-Path -LiteralPath $script:IdentityEnvironmentFile -PathType Leaf) -and -not $Force) {
    $existingKeys = @{}
    foreach ($rawLine in Get-Content -LiteralPath $script:IdentityEnvironmentFile) {
        $line = $rawLine.Trim()
        if (-not $line -or $line.StartsWith("#", [System.StringComparison]::Ordinal) -or -not $line.Contains("=")) {
            continue
        }
        $existingKeys[$line.Split("=", 2)[0].Trim()] = $true
    }
    if (-not $existingKeys.ContainsKey("NORTHLAKE_CUSTOMER_CLIENT_SECRET")) {
        if (-not $PSCmdlet.ShouldProcess($script:IdentityEnvironmentFile, "Add the Phase 7 synthetic customer client secret")) {
            return
        }
        Add-Content -LiteralPath $script:IdentityEnvironmentFile -Encoding utf8NoBOM -Value @(
            "",
            "# Separate confidential client used only by the synthetic customer website.",
            "NORTHLAKE_CUSTOMER_CLIENT_SECRET=$(New-IdentitySecret)"
        )
        Write-Host "[OK] Added the Phase 7 synthetic customer client secret."
    }
    else {
        Write-Host "[OK] Identity environment already exists: $script:IdentityEnvironmentFile"
    }
    Write-Host "Use -Force to replace all local identity secrets."
    return
}

if (-not $PSCmdlet.ShouldProcess($script:IdentityEnvironmentFile, "Generate local identity secrets")) {
    return
}

$lines = @(
    "# Generated by Initialize-Identity.ps1. Do not commit this file.",
    "IDENTITY_HOST=localhost",
    "IDENTITY_HTTPS_PORT=8443",
    "IDENTITY_BIND_ADDRESS=127.0.0.1",
    "IDENTITY_PUBLIC_BASE_URL=https://localhost:8443",
    "NORTHLAKE_PROVIDER_DISPLAY_NAME=Northlake Synthetic Identity",
    "NORTHLAKE_REALM_KEY=northlake",
    "NORTHLAKE_ENABLE_OIDC=true",
    "NORTHLAKE_ENABLE_SAML=true",
    "",
    "KEYCLOAK_ADMIN=admin",
    "KEYCLOAK_ADMIN_PASSWORD=$(New-IdentitySecret -AsPassword)",
    "KEYCLOAK_DB_PASSWORD=$(New-IdentitySecret -AsPassword)",
    "",
    "EEMSUITE_OIDC_CLIENT_SECRET=$(New-IdentitySecret)",
    "EEMSUITE_OIDC_LEGACY_CLIENT_SECRET=$(New-IdentitySecret)",
    "NORTHLAKE_CUSTOMER_CLIENT_SECRET=$(New-IdentitySecret)",
    "SYNTHETIC_USER_PASSWORD=$(New-IdentitySecret -AsPassword)",
    "",
    "EEMSUITE_APPLICATION_HOME_URL=https://localdev.energyhippo.com/Hippo/",
    "EEMSUITE_OIDC_REDIRECT_URIS=https://localhost:7310/signin-oidc;https://localdev.energyhippo.com/Hippo/signin-oidc;https://localhost/Hippo/signin-oidc",
    "",
    "EEMSUITE_SAML_PROFILES=Standard",
    "EEMSUITE_SAML_STANDARD_ENTITY_ID=urn:energyhippo:eemsuite-web:saml:standard",
    "EEMSUITE_SAML_STANDARD_ACS_URLS=https://localhost:7310/saml/northlake-saml-standard/acs;https://localdev.energyhippo.com/Hippo/saml/northlake-saml-standard/acs;https://localhost/Hippo/saml/northlake-saml-standard/acs",
    "EEMSUITE_SAML_STANDARD_LOGOUT_URLS=https://localhost:7310/saml/northlake-saml-standard/logout;https://localdev.energyhippo.com/Hippo/saml/northlake-saml-standard/logout;https://localhost/Hippo/saml/northlake-saml-standard/logout",
    "",
    "# Add Saml2Int only after exporting EEMSuite's public service-provider certificate.",
    "EEMSUITE_SAML2INT_ENTITY_ID=urn:energyhippo:eemsuite-web:saml:saml2int",
    "EEMSUITE_SAML2INT_ACS_URLS=https://localdev.energyhippo.com/Hippo/saml/northlake-saml2int/acs;https://localhost/Hippo/saml/northlake-saml2int/acs",
    "EEMSUITE_SAML2INT_LOGOUT_URLS=https://localdev.energyhippo.com/Hippo/saml/northlake-saml2int/logout;https://localhost/Hippo/saml/northlake-saml2int/logout",
    "EEMSUITE_SAML2INT_SP_CERTIFICATE_FILE="
)

$lines | Set-Content -LiteralPath $script:IdentityEnvironmentFile -Encoding utf8NoBOM
Write-Host "[OK] Generated local identity secrets: $script:IdentityEnvironmentFile"
Write-Host "The file is ignored by Git. Test user and client credentials will also be written"
Write-Host "to identity\.runtime\connection.json when the stack starts."
