[CmdletBinding(SupportsShouldProcess, ConfirmImpact = "High")]
param(
    [switch] $Force
)

. (Join-Path $PSScriptRoot "Identity.Common.ps1")

if ((Test-Path -LiteralPath $script:IdentityEnvironmentFile -PathType Leaf) -and -not $Force) {
    Write-Host "[OK] Identity environment already exists: $script:IdentityEnvironmentFile"
    Write-Host "Use -Force to replace all local identity secrets."
    return
}

if (-not $PSCmdlet.ShouldProcess($script:IdentityEnvironmentFile, "Generate local identity secrets")) {
    return
}

function New-IdentitySecret {
    param(
        [int] $ByteCount = 32,
        [switch] $AsPassword
    )

    $bytes = [byte[]]::new($ByteCount)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $token = [Convert]::ToBase64String($bytes).TrimEnd("=").Replace("+", "-").Replace("/", "_")
    if ($AsPassword) {
        return "A1!$token"
    }
    return $token
}

$lines = @(
    "# Generated by Initialize-Identity.ps1. Do not commit this file.",
    "IDENTITY_HOST=localhost",
    "IDENTITY_HTTPS_PORT=8443",
    "IDENTITY_BIND_ADDRESS=127.0.0.1",
    "IDENTITY_PUBLIC_BASE_URL=https://localhost:8443",
    "",
    "KEYCLOAK_ADMIN=admin",
    "KEYCLOAK_ADMIN_PASSWORD=$(New-IdentitySecret -AsPassword)",
    "KEYCLOAK_DB_PASSWORD=$(New-IdentitySecret -AsPassword)",
    "",
    "EEMSUITE_OIDC_CLIENT_SECRET=$(New-IdentitySecret)",
    "EEMSUITE_OIDC_LEGACY_CLIENT_SECRET=$(New-IdentitySecret)",
    "SYNTHETIC_USER_PASSWORD=$(New-IdentitySecret -AsPassword)",
    "",
    "EEMSUITE_APPLICATION_HOME_URL=https://localdev.energyhippo.com/Hippo/",
    "EEMSUITE_OIDC_REDIRECT_URIS=https://localhost:7310/signin-oidc;https://localdev.energyhippo.com/Hippo/signin-oidc;https://localhost/Hippo/signin-oidc",
    "",
    "EEMSUITE_SAML_ENTITY_ID=urn:energyhippo:eemsuite-web:saml",
    "EEMSUITE_SAML_ACS_URLS=https://localhost:7310/saml/acs;https://localdev.energyhippo.com/Hippo/saml/acs;https://localhost/Hippo/saml/acs",
    "EEMSUITE_SAML_LOGOUT_URLS=https://localhost:7310/saml/logout;https://localdev.energyhippo.com/Hippo/saml/logout;https://localhost/Hippo/saml/logout"
)

$lines | Set-Content -LiteralPath $script:IdentityEnvironmentFile -Encoding utf8NoBOM
Write-Host "[OK] Generated local identity secrets: $script:IdentityEnvironmentFile"
Write-Host "The file is ignored by Git. Test user and client credentials will also be written"
Write-Host "to identity\.runtime\connection.json when the stack starts."
